# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-06-03 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_remove_has_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlocale',
            name='readonly',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='links',
            field=models.BooleanField(default=False, help_text=b'\n        Keep links on the project website clickable.\n    ', verbose_name=b'Clickable links'),
        ),
        migrations.AlterField(
            model_name='project',
            name='width',
            field=models.PositiveIntegerField(blank=True, help_text=b'\n        Default website (iframe) width in pixels. If set, sidebar will be\n        opened by default.\n    ', null=True),
        ),
    ]
