# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-01-22 00:58
from __future__ import unicode_literals

from django.db import migrations


CREATE_FILTERS_SQL = 'INSERT INTO base_entityfilters (entity_id) SELECT id FROM base_entity'
REMOVE_FILTERS_SQL = 'DELETE FROM base_entityfilters'


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_entityfilters'),
    ]

    operations = [
        migrations.RunSQL(CREATE_FILTERS_SQL, REMOVE_FILTERS_SQL)
    ]
