# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:46
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations, models
import pontoon.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_create_filters_for_entities'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='search_index',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='search_index',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
