# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 21:49
from __future__ import unicode_literals

from django.db import migrations

from pontoon.base.search_migrations import CreateGINIndex, UpdateSearchIndex

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_auto_20170226_2146'),
    ]

    operations = [
        CreateGINIndex('base_entity', 'search_index'),
        CreateGINIndex('base_translation', 'search_index'),
        UpdateSearchIndex('base_entity', 'search_index', ['string', 'string_plural', 'comment', 'key']),
        UpdateSearchIndex('base_translation', 'search_index', ['string']),
    ]
