# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 11:59
from __future__ import unicode_literals

from bulk_update.helper import bulk_update
from django.db import migrations

import time

from django.db.models import Prefetch

import pontoon.base.models


def migrate_entity_statuses(apps, schema_editor):
    Locale = apps.get_model('base', 'Locale')
    Entity = apps.get_model('base', 'Entity')
    EntityFilters = apps.get_model('base', 'EntityFilters')
    Translation = apps.get_model('base', 'Translation')

    filters_batch = []
    start = time.time()
    entities = Entity.objects.prefetch_related(
        Prefetch(
            'translation_set',
            queryset=Translation.objects.prefetch_related('locale'),
            to_attr='prefetched_translations'
        )
    )
    entities = list(entities)
    print "Loaded entities", time.time() - start
    for i, entity in enumerate(entities):
        # start_time = time.time()
        filters_entity = EntityFilters.objects.get(entity=entity)

        for locale in Locale.objects.all():
            EntityFilters.objects.update_filters_state(entity, locale, filters_entity, commit=True)

        # bulk_time= time.time()
        # filters_batch.append(filters_entity)
        # if not(len(filters_batch) % 1000):
        #     bulk_update(filters_batch)
        #     filters_batch = []
    #
    # if filters_batch:
    #     bulk_update(filters_batch)



class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_search_index_triggers_and_indexes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='entityfilters',
            managers=[
                ('objects', pontoon.base.models.EntityFiltersManager()),
            ],
        ),
        migrations.RunPython(migrate_entity_statuses, migrations.RunPython.noop)
    ]
