# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_improve_calculate_stats_performance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_path', models.TextField()),
                ('resource_format', models.CharField(max_length=20)),
                ('entity_string', models.TextField()),
                ('entity_key', models.TextField(blank=True)),
                ('entity_comment', models.TextField(blank=True)),
                ('entity_order', models.PositiveIntegerField()),
                ('entity_source', jsonfield.fields.JSONField(blank=True, default=list)),
                ('translation_string', models.TextField(blank=True, null=True)),
                ('translation_author', models.TextField(blank=True, null=True)),
                ('translation_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'translated', b'translated'), (b'suggested', b'suggested'), (b'fuzzy', b'fuzzy'), (b'missing', b'missing')], max_length=10)),
                ('has_suggestions', models.BooleanField(default=False)),
                ('unchanged', models.BooleanField(default=False)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Locale')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Project')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Resource')),
                ('translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Translation')),
            ],
        ),
    ]
