# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 18:33
from __future__ import unicode_literals

from django.db import migrations


def populate_active_translation(apps, schema_editor):
    ActiveTranslation = apps.get_model('base', 'ActiveTranslation')
    Entity = apps.get_model('base', 'Entity')
    Locale = apps.get_model('base', 'Locale')

    for locale in Locale.objects.all():
        entities_array = []
        entities = (
            Entity.objects
            .filter(resource__translatedresources__locale=locale, obsolete=False)
            .prefetch_resources_translations(locale)
        )

        for entity in entities:
            if entity.string_plural == "":
                translation = entity.get_translation()
                if not translation['pk']:
                    status = 'missing'
                elif translation['approved']:
                    status = 'approved'
                elif translation['fuzzy']:
                    status = 'fuzzy'
                else:
                    status = 'suggested'
            else:
                continue

            entities_array.append(ActiveTranslation(**{
                'locale_id': locale.pk,
                'project_id': entity.resource.project.pk,
                'resource_id': entity.resource.pk,
                'entity_id': entity.pk,
                'translation_id': translation['pk'],
                'resource_path': entity.resource.path,
                'resource_format': entity.resource.format,
                'entity_string': entity.string,
                'entity_key': entity.cleaned_key,
                'entity_comment': entity.comment,
                'entity_order': entity.order,
                'entity_source': entity.source,
                'translation_string': translation['string'],
                'translation_author': translation['author'],
                'translation_date': translation['date'],
                'status': status,
                'has_suggestions': len(entity.fetched_translations) > 1,
                'unchanged': translation['string'] == entity.string,
            }))

        ActiveTranslation.objects.bulk_create(entities_array)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_activetranslation'),
    ]

    operations = [
        migrations.RunPython(populate_active_translation, migrations.RunPython.noop),
    ]
